import { BaseCreepProfile } from "./BaseCreepProfile";

/**
 * Hauler creep profile, designed to carry resources from haulers to extensions, containers, etc..
 * THe hauler maximize the transport efficiency, having  just the right amount of move part to recover from
 * the max fatigue generated by its carry parts.
 */
export class GeneralPurpose extends BaseCreepProfile {
    constructor() {
        super("GeneralPurpose", [CARRY, WORK, MOVE]);
    }

    private nextPartForLevel(level: number) {
        if ([0, 3, 6, 8].includes(level % 10)) {
            return CARRY;
        } else if ([1, 4, 7, 9].includes(level % 10)) {
            return WORK;
        } else {
            return MOVE;
        }
    }

    public incrementLevel(): void {
        this.bodyParts.push(this.nextPartForLevel(this.level));
        this.level += 1;
    }

    public decrementLevel(): void {
        this.bodyParts = this.bodyParts.slice(0, -1);
        this.level -= 1;
    }
}
