import { COLORS, getLogger } from "utils/Logger";
import { BaseCreepProfile } from "./BaseCreepProfile";

const logger = getLogger("colony.creepProfiles.GeneralPurpose", COLORS.colony);

/**
 * Hauler creep profile, designed to carry resources from haulers to extensions, containers, etc..
 * THe hauler maximize the transport efficiency, having  just the right amount of move part to recover from
 * the max fatigue generated by its carry parts.
 */
export class GeneralPurpose extends BaseCreepProfile {
    constructor() {
        super("GeneralPurpose", [CARRY, WORK, MOVE]);
    }

    public incrementLevel(): void {
        // logger.info(`level ${this.level}: cost: ${this.cost()} for parts: ${this.bodyParts.join(",")}`);
        this.bodyParts.push(CARRY);
        this.bodyParts.push(WORK);
        this.bodyParts.push(MOVE);
        this.bodyParts.push(MOVE);
        this.level += 1;
        // logger.info(`level ${this.level}: cost: ${this.cost()} for parts: ${this.bodyParts.join(",")}`);
    }
}
