import { _cost, BaseCreepProfile } from "./BaseCreepProfile";

/**
 * Hauler creep profile, designed to carry resources from haulers to extensions, containers, etc..
 * THe hauler maximize the transport efficiency, having  just the right amount of move part to recover from
 * the max fatigue generated by its carry parts.
 */
export class Hauler extends BaseCreepProfile {
    constructor(availableEnergy: number) {
        const bodyParts = [CARRY, MOVE];
        let level = 1;
        while (_cost(bodyParts) < availableEnergy) {
            bodyParts.push(CARRY);
            bodyParts.push(MOVE);
            level += 1;
        }
        super("Hauler", level - 1, bodyParts.slice(0, -2));
    }
}
