import { BaseCreepProfile } from "./BaseCreepProfile";

/**
 * Hauler creep profile, designed to carry resources from haulers to extensions, containers, etc..
 * THe hauler maximize the transport efficiency, having  just the right amount of move part to recover from
 * the max fatigue generated by its carry parts.
 */
export class Hauler extends BaseCreepProfile {
    constructor() {
        super("Hauler", [CARRY, MOVE]);
    }

    public incrementLevel(): void {
        this.bodyParts.push(CARRY);
        this.bodyParts.push(MOVE);
        this.level += 1;
    }
}
